CREATE TABLE `ele_rexiao` (
  `poi_id` int(15) NOT NULL,
  `food_namefirst` varchar(50) DEFAULT NULL,
  `food_namefirst_price` float DEFAULT NULL,
  `food_namefirst_msale` int(15) DEFAULT NULL,
  `food_namesecond` varchar(50) DEFAULT NULL,
  `food_namesecond_price` float DEFAULT NULL,
  `food_namesecond_msale` int(15) DEFAULT NULL,
  `food_namethird` varchar(50) DEFAULT NULL,
  `food_namethird_price` float DEFAULT NULL,
  `food_namethird_msale` int(15) DEFAULT NULL,
  `food_namefour` varchar(50) DEFAULT NULL,
  `food_namefour_price` float DEFAULT NULL,
  `food_namefour_msale` int(15) DEFAULT NULL,
  `food_namefive` varchar(50) DEFAULT NULL,
  `food_namefive_price` float DEFAULT NULL,
  `food_namefive_msale` int(15) DEFAULT NULL,
  `food_namesix` varchar(50) DEFAULT NULL,
  `food_namesix_price` float DEFAULT NULL,
  `food_namesix_msale` int(15) DEFAULT NULL,
  `food_nameseven` varchar(50) DEFAULT NULL,
  `food_nameseven_price` float DEFAULT NULL,
  `food_nameseven_msale` int(15) DEFAULT NULL,
  `food_nameeight` varchar(50) DEFAULT NULL,
  `food_nameeight_price` float DEFAULT NULL,
  `food_nameeight_msale` int(15) DEFAULT NULL,
  `food_namenine` varchar(50) DEFAULT NULL,
  `food_namenine_price`float DEFAULT NULL,
  `food_namenine_msale` int(15) DEFAULT NULL,
  `food_nameten` varchar(50) DEFAULT NULL,
  `food_nameten_price` float DEFAULT NULL,
  `food_nameten_msale` int(15) DEFAULT NULL,
  PRIMARY KEY (`poi_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

